use super::*;

pub use self::add::*;
pub use self::add_immediate::*;
pub use self::branch::*;
pub use self::branch_immediate::*;
pub use self::call::*;
pub use self::clone_local::*;
pub use self::discard::*;
pub use self::drop::*;
pub use self::drop_immediate::*;
pub use self::exit::*;
pub use self::jump::*;
pub use self::recall::*;
pub use self::reset::*;
pub use self::return_operation::*;
pub use self::reversal_hint::*;
pub use self::reverser::*;
pub use self::swap::*;

mod reverser;
mod swap;
mod add;
mod add_immediate;
mod drop;
mod drop_immediate;
mod discard;
mod reset;
mod call;
mod recall;
mod jump;
mod branch;
mod branch_immediate;
mod clone_local;
mod return_operation;
mod exit;
mod reversal_hint;
